version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${IMONGR_DB_NAME}
      MYSQL_USER: ${IMONGR_DB_USER}
      MYSQL_PASSWORD: ${IMONGR_DB_PASS}
    volumes:
      - ./mdbdata/imongr:/var/lib/mysql
      - ./mdbdata/imongr_init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: db
        awslogs-stream: imongr
        awslogs-create-group: "true"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: db
        awslogs-stream: adminer
        awslogs-create-group: "false"
